services:
  db:
    image: postgres
    container_name: mst_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: mst_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # This is go modules cache, without it you will have to
      # re-download all dependencies after restarting container
      - /go/pkg/mod/cache
      - ./:/code:cached
    environment:
      ENV: dev
      API_KEY: ${API_KEY}
      COGNITO_POOL_ID: ${COGNITO_POOL_ID}
      DEV_DB_URL: ${DEV_DB_URL}
      PORT: 8080
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
