--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15
-- Dumped by pg_dump version 14.17 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: licence_type_enum; Type: TYPE; Schema: public; Owner: mst_admin
--

CREATE TYPE public.licence_type_enum AS ENUM (
    'trial',
    'paid',
    'beta'
);


ALTER TYPE public.licence_type_enum OWNER TO mst_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: mst_admin
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO mst_admin;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: mst_admin
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: licences; Type: TABLE; Schema: public; Owner: mst_admin
--

CREATE TABLE public.licences (
    licence_key text DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    machine_id text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_used_at timestamp without time zone,
    licence_type public.licence_type_enum,
    expiry date
);


ALTER TABLE public.licences OWNER TO mst_admin;

--
-- Name: users; Type: TABLE; Schema: public; Owner: mst_admin
--

CREATE TABLE public.users (
    email text NOT NULL,
    has_license boolean NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    number_of_licenses integer DEFAULT 0 NOT NULL,
    subscribed_to_emails boolean DEFAULT false NOT NULL,
    full_name character varying(255) DEFAULT ''::character varying NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public.users OWNER TO mst_admin;

--
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: mst_admin
--

COPY public.goose_db_version (id, version_id, is_applied, tstamp) FROM stdin;
1	0	t	2025-05-02 23:14:43.760705
2	20250502230618	t	2025-05-02 23:18:27.67492
3	20250502230627	t	2025-05-02 23:18:29.065052
4	20250502231708	t	2025-05-02 23:18:29.845137
7	20250502232041	t	2025-05-02 23:54:20.638737
8	20250502234917	t	2025-05-02 23:54:22.1119
9	20250502235627	t	2025-05-02 23:59:03.560775
34	20250508020356	t	2025-05-08 02:16:19.601386
67	20250508124535	t	2025-05-08 12:59:55.769419
68	20250508135350	t	2025-05-08 14:14:49.010065
100	20250524012429	t	2025-05-24 05:07:12.044972
101	20250524013201	t	2025-05-24 05:07:13.610873
133	20250527131028	t	2025-05-27 13:19:05.519086
166	20250528030134	t	2025-05-28 03:15:36.399627
\.


--
-- Data for Name: licences; Type: TABLE DATA; Schema: public; Owner: mst_admin
--

COPY public.licences (licence_key, user_id, machine_id, created_at, last_used_at, licence_type, expiry) FROM stdin;
6ed600f6-3503-4ca9-a8e8-ff93c50bc118	e93919be-10a1-70c8-385b-c006812f9142	ee7a4e11cfd3ea1c6bf483a6b90e7f4bb840882c57a03509486c9d06f0030fbb	2025-05-24 05:07:13.610873	2025-05-24 05:07:13.610873	paid	\N
ca9fe6ba-f482-4bb3-807c-06b7a32e0a99	1db733cc-2809-47bb-b34d-93dea56c250a	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
bcfcd202-8854-4291-b903-2fe4fc30a66b	e0716cb4-8d98-4729-8f42-4d1390480b30	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
2e3af351-87cd-4aa5-bf64-c7dd9911de41	4bd8de8d-3cc0-4370-b85c-1a614a9a957a	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
85a42be6-0bfd-4170-bdee-282073771dbf	6db55731-3b37-4d9f-b478-f55ea5542da6	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
0b876821-ddcf-4c4c-8ad5-7d2ab0f5181e	4da573fa-9697-49bf-8a84-df56e357f42f	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
d9126b50-169b-4f55-b94a-a83cbdc33ac5	a34661ba-e066-48c2-aead-5e4ca2267f4f	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
9f681bee-1230-4950-bccc-8401e099bce3	303854d9-871c-4412-ae04-8275322c48ac	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
0702ee62-5dee-436c-b114-d5ae9157dbf4	b86b776a-8cbf-4de8-825e-2adea6e795ca	\N	2025-05-28 03:15:36.399627	2025-05-28 03:15:36.399627	beta	2025-08-26
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: mst_admin
--

COPY public.users (email, has_license, created_at, number_of_licenses, subscribed_to_emails, full_name, id) FROM stdin;
hughpalmerproduction@gmail.com	f	2025-05-13 02:44:26.372671	0	f	Hugh Palmer	e93919be-10a1-70c8-385b-c006812f9142
palmerhap@gmail.com	t	2025-05-28 03:15:36.399627	1	t	Hugh Palmer	1db733cc-2809-47bb-b34d-93dea56c250a
davidrossaudio@gmail.com	t	2025-05-28 03:15:36.399627	1	t	David Ross	e0716cb4-8d98-4729-8f42-4d1390480b30
cutsnake@netspace.net.au	t	2025-05-28 03:15:36.399627	1	t	Terry Chadwick	4bd8de8d-3cc0-4370-b85c-1a614a9a957a
Ale.cesana88@gmail.com	t	2025-05-28 03:15:36.399627	1	t	Ale Cesana	6db55731-3b37-4d9f-b478-f55ea5542da6
ryan@deadonsound.com	t	2025-05-28 03:15:36.399627	1	t	Ryan Granger	4da573fa-9697-49bf-8a84-df56e357f42f
paul_isaacs@sounddevices.com	t	2025-05-28 03:15:36.399627	1	t	Paul Isaacs	a34661ba-e066-48c2-aead-5e4ca2267f4f
josh@camelcitysound.net	t	2025-05-28 03:15:36.399627	1	t	Josh Tucker	303854d9-871c-4412-ae04-8275322c48ac
lukearmstrong@me.com	t	2025-05-28 03:15:36.399627	1	t	Luke Armstrong	b86b776a-8cbf-4de8-825e-2adea6e795ca
\.


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mst_admin
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 198, true);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: mst_admin
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: licences licences_pkey; Type: CONSTRAINT; Schema: public; Owner: mst_admin
--

ALTER TABLE ONLY public.licences
    ADD CONSTRAINT licences_pkey PRIMARY KEY (licence_key);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: mst_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: mst_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: licences licences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: mst_admin
--

ALTER TABLE ONLY public.licences
    ADD CONSTRAINT licences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: mst_admin
--

REVOKE ALL ON SCHEMA public FROM rdsadmin;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO mst_admin;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

