// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type EmailTypes string

const (
	EmailTypesMarketingInvite    EmailTypes = "marketing_invite"
	EmailTypesTrialLicenceExpiry EmailTypes = "trial_licence_expiry"
)

func (e *EmailTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmailTypes(s)
	case string:
		*e = EmailTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for EmailTypes: %T", src)
	}
	return nil
}

type NullEmailTypes struct {
	EmailTypes EmailTypes
	Valid      bool // Valid is true if EmailTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmailTypes) Scan(value interface{}) error {
	if value == nil {
		ns.EmailTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmailTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmailTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmailTypes), nil
}

type LicenceTypeEnum string

const (
	LicenceTypeEnumTrial LicenceTypeEnum = "trial"
	LicenceTypeEnumPaid  LicenceTypeEnum = "paid"
	LicenceTypeEnumBeta  LicenceTypeEnum = "beta"
)

func (e *LicenceTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LicenceTypeEnum(s)
	case string:
		*e = LicenceTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for LicenceTypeEnum: %T", src)
	}
	return nil
}

type NullLicenceTypeEnum struct {
	LicenceTypeEnum LicenceTypeEnum
	Valid           bool // Valid is true if LicenceTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLicenceTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.LicenceTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LicenceTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLicenceTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LicenceTypeEnum), nil
}

type AppMessage struct {
	Email              string
	CreatedAt          sql.NullTime
	NumberOfLicenses   int32
	SubscribedToEmails bool
	FullName           string
	ID                 uuid.UUID
}

type AppRelease struct {
	ID             uuid.UUID
	Platform       string
	Architecture   sql.NullString
	ReleaseVersion string
	UrlFilename    string
	FileSize       sql.NullInt64
	ReleaseDate    sql.NullTime
	IsLatest       sql.NullBool
	ReleaseNotes   sql.NullString
	CreatedAt      sql.NullTime
}

type BetaLicence struct {
	Email sql.NullString
	Seen  bool
	Name  sql.NullString
}

type Licence struct {
	LicenceKey  string
	UserID      uuid.UUID
	MachineID   sql.NullString
	CreatedAt   sql.NullTime
	LastUsedAt  sql.NullTime
	LicenceType NullLicenceTypeEnum
	Expiry      sql.NullTime
	Jti         uuid.NullUUID
}

type SentEmail struct {
	ID             uuid.UUID
	UserID         uuid.NullUUID
	EmailType      EmailTypes
	RecipientEmail string
	SentAt         sql.NullTime
	Status         string
	ErrorMessage   sql.NullString
}

type StripeEvent struct {
	ID          string
	Type        string
	ProcessedAt sql.NullTime
}

type TrialMachine struct {
	MachineID string
	UserID    uuid.NullUUID
	ClaimedAt sql.NullTime
}

type User struct {
	Email              string
	CreatedAt          sql.NullTime
	NumberOfLicences   int32
	SubscribedToEmails bool
	FullName           string
	ID                 uuid.UUID
	StripeID           sql.NullString
}
