// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const changeMachineID = `-- name: ChangeMachineID :exec
UPDATE licences
SET machine_id = $2
WHERE licence_key = $1
`

type ChangeMachineIDParams struct {
	LicenceKey string
	MachineID  sql.NullString
}

func (q *Queries) ChangeMachineID(ctx context.Context, arg ChangeMachineIDParams) error {
	_, err := q.db.ExecContext(ctx, changeMachineID, arg.LicenceKey, arg.MachineID)
	return err
}

const getLicence = `-- name: GetLicence :one
SELECT licence_key, user_id, machine_id, created_at, last_used_at, licence_type, expiry FROM licences
where licence_key = $1 LIMIT 1
`

func (q *Queries) GetLicence(ctx context.Context, licenceKey string) (Licence, error) {
	row := q.db.QueryRowContext(ctx, getLicence, licenceKey)
	var i Licence
	err := row.Scan(
		&i.LicenceKey,
		&i.UserID,
		&i.MachineID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.LicenceType,
		&i.Expiry,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT email, has_license, created_at, number_of_licenses, subscribed_to_emails, full_name, id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.Email,
		&i.HasLicense,
		&i.CreatedAt,
		&i.NumberOfLicenses,
		&i.SubscribedToEmails,
		&i.FullName,
		&i.ID,
	)
	return i, err
}

const removeMachineID = `-- name: RemoveMachineID :exec
UPDATE licences
SET machine_id = null
WHERE licence_key = $1
`

func (q *Queries) RemoveMachineID(ctx context.Context, licenceKey string) error {
	_, err := q.db.ExecContext(ctx, removeMachineID, licenceKey)
	return err
}
