name: "Email Expired Licence Users"
on:
  # schedule:
  #   - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  cron_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make curl request to backend
        run: |
          curl -f -X POST "${{secrets.API_URL}}/cron-email-expired-licences" \
          -H "Content-Type: application/json" \
          -H "X-API-Key: ${{secrets.X_API_KEY}}"
